#!/bin/bash

for file in lwb/*.ksp;
do
    echo "Processing file $file" 
    exec 5>&1
    echo "Processing file $file" &>> $file.ord.log
    /usr/bin/time -f "%U %S %e seconds"  /usr/bin/timeout 10s ./ksp-0.1.2/ksp -c ksp-0.1.2/conf.files/jose_max.conf -i $file &> logs/max/$file.ord.log
    if [ $? -eq 124 ]; then echo "Unable" &>>$file.ord.log; fi
    if [ $? -eq 139 ]; then echo "Fail" &>>$file.ord.log; fi
    exec 1>&5 5>&- 
done

#Recovers stdout from file descriptor 5
# exec 1>&5 5>&-  
